### ISSUE TITLE
Installing hmap from milend/taps got this error

### ISSUE THREAD

**Issue by michellepandev** [milend/homebrew-taps#3]
brew install milend/taps/hmap
==> Installing hmap from milend/taps
==> Downloading https://github.com/milend/hmap/archive/1.0.3.tar.gz
Already downloaded: /Users/ft/Library/Caches/Homebrew/downloads/aed91e152d8a3b99d66cc2b9acff4757f230b213231cedccbdf1f34f8924a1b6--hmap-1.0.3.tar.gz
==> swift build --disable-sandbox -c release -Xswiftc -static-stdlib
Last 15 lines from /Users/ft/Library/Logs/Homebrew/hmap/01.swift:
      _$s9Commander15ANSIConvertiblePAAE5printyyF in Error.swift.o
      _$s13HeaderMapCore010JSONHeaderB0V8jsonDataAC10Foundation0F0V_tKcfC in JSONHeaderMap.swift.o
      _$s13HeaderMapCore010JSONHeaderB0V12makeJSONData13prettyPrinted10Foundation4DataVSb_tKF in JSONHeaderMap.swift.o
  "_swift_unknownObjectRetain", referenced from:
      _$ss12_ArrayBufferV19_getElementSlowPathyyXlSiF9Commander23BoxedArgumentDescriptorC_Tg5 in ArgumentDescription.swift.o
  "_swift_willThrow", referenced from:
      _$sSS9CommanderE6parserSSAA14ArgumentParserC_tKcfC in ArgumentConvertible.swift.o
      _$sSS9Commander19ArgumentConvertibleA2aBP6parserxAA0B6ParserC_tKcfCTW in ArgumentConvertible.swift.o
      _$sSi9Commander19ArgumentConvertibleA2aBP6parserxAA0B6ParserC_tKcfCTW in ArgumentConvertible.swift.o
      _$sSf9Commander19ArgumentConvertibleA2aBP6parserxAA0B6ParserC_tKcfCTW in ArgumentConvertible.swift.o
      _$sSd9Commander19ArgumentConvertibleA2aBP6parserxAA0B6ParserC_tKcfCTW in ArgumentConvertible.swift.o
      _$sSi9CommanderE6parserSiAA14ArgumentParserC_tKcfCTf4gd_n in ArgumentConvertible.swift.o
      _$sSfySfSgxcSyRzlufCSS_Tg5Tf4gXd_n in ArgumentConvertible.swift.o
      ...
ld: symbol(s) not found for architecture x86_64

**Comment by milend** [comment]
This is now fixed with hmap v1.0.4 – the root issue was that Xcode 10.2 / Swift 5 no longer support statically linking the runtime libraries. You can update the package using `brew upgrade hmap`.
